//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Domain
{
        using System.ComponentModel.DataAnnotations; //引入DataMeta空间
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(BlogUsersMeta))]  //metaTypeGenerate
    public partial class BlogUsers:MyBaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogUsers()
        {
            this.IsDel = false;
            this.BlogTags = new HashSet<BlogTags>();
            this.Blogs = new HashSet<Blogs>();
            this.BlogTypes = new HashSet<BlogTypes>();
            this.BlogComments = new HashSet<BlogComments>();
            this.UserFiles = new HashSet<UserFiles>();
            this.ReadInfo = new HashSet<ReadInfo>();
        }
    
        public int UserId { get; set; }
        public System.DateTime CreateTime { get { return base.CreateTime; } set { base.CreateTime = value; } }
        public Nullable<System.DateTime> UpTime { get { return base.UpTime; } set { base.UpTime = value; } }
        public bool IsDel { get { return base.IsDel; } set { base.IsDel = value; } }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public string UserNickname { get; set; }
        public string Portrait { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> DefaultCSS { get; set; }
        public Nullable<bool> HasCSS { get; set; }
        public Nullable<bool> HasHTML { get; set; }
        public Nullable<bool> HasJS { get; set; }
        public Nullable<int> Theme { get; set; }
        public string Introduction { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> Age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogTags> BlogTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blogs> Blogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogTypes> BlogTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogComments> BlogComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFiles> UserFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadInfo> ReadInfo { get; set; }
    }
}
