//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Domain
{
        using System.ComponentModel.DataAnnotations; //引入DataMeta空间
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(BlogCommentsMeta))]  //metaTypeGenerate
    public partial class BlogComments:MyBaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogComments()
        {
            this.IsDel = false;
            this.IsReply = false;
        }
    
        public int BlogCommentId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateTime { get { return base.CreateTime; } set { base.CreateTime = value; } }
        public Nullable<System.DateTime> UpTime { get { return base.UpTime; } set { base.UpTime = value; } }
        public bool IsDel { get { return base.IsDel; } set { base.IsDel = value; } }
        public bool IsReply { get; set; }
        public Nullable<int> ToCommentId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public int BlogId { get; set; }
        public int UserId { get; set; }
    
        public virtual Blogs Blogs { get; set; }
        public virtual BlogUsers BlogUsers { get; set; }
    }
}
