//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Domain
{
        using System.ComponentModel.DataAnnotations; //引入DataMeta空间
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(UserFilesMeta))]  //metaTypeGenerate
    public partial class UserFiles:MyBaseModel
    {
        public int FileId { get; set; }
        public string FileName { get; set; }
        public bool IsImage { get; set; }
        public string FileUrl { get; set; }
        public double FileSize { get; set; }
        public int UserId { get; set; }
    
        public virtual BlogUsers BlogUsers { get; set; }
    }
}
